language: php

php:
  - 7.3

env:
  - APP_ENV=testing DB_CONNECTION=sqlite DB_DATABASE="database/database.sqlite"

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer install --prefer-dist --no-interaction
  - touch database/database.sqlite
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan passport:install

script:
  - vendor/bin/phpunit  --testdox --verbose
